### PR TITLE
Fix style path for release builds

### LINKED ISSUE #5: Release builds fail
Currently release builds of Ebou fail due to a mistake in the build script.

```rust
#[cfg(not(debug_assertions))]
fn styles() -> String {
    grass::include!("../public/style.css").to_string()
}
```

is probably meant to be 

```rust
#[cfg(not(debug_assertions))]
fn styles() -> String {
    grass::include!("public/style.scss").to_string()
}
```

### PR DESCRIPTION
**Pull request by Cyborus04**
Currently `cargo build --release` fails because this file does not exist. Adjusts the path to the one that does exist.

Fixes #5

### CODE REVIEW

**Comment by Cyborus04** [comment]
ah, looks like I'm not the only one who noticed that. #5

File: build.rs [hunk 1]
```diff
@@ -13,7 +13,7 @@ fn styles() -> String {
 
 #[cfg(not(debug_assertions))]
 fn styles() -> String {
-    grass::include!("../public/style.css").to_string()
+    grass::include!("../public/style.scss").to_string()
```
Comment (aumetra) [inline build.rs]: Shouldn't the path look like this? The build script is in the same directory as the `public` directory

```suggestion
    grass::include!("public/style.scss").to_string()
```

Comment (Cyborus04) [reply build.rs]: ah shoot yeah

**Comment by terhechte** [comment]
Thanks for the fix! Sorry for merging it so late but I had a couple of terribly busy work days

**Comment by Cyborus04** [comment]
No worries :)
